alert('Calculo do Perimetro do Retângulo')
let base=Number(prompt('Insira o valor da Base do Retângulo: '))
let altura=Number(prompt('Insira o valor da altura do Retângulo: '))
let perimetro=2*(base+altura)
alert('O valor do perimetro é: ' + perimetro)